### ISSUE TITLE
Parse Generator<mixed, mixed, mixed, T> docs and validate the type of return value

### ISSUE THREAD

**Issue by Endermanbugzjfc** [SOF3/await-generator#117]
A little enhancement to help to debug and prevent unexpected behaviour. Although PHPStorm can already warn users.

**Comment by Endermanbugzjfc** [comment]
> I don't understand what you mean. Who parses this doc? When does it parse this doc?

Await-generator should parse the doc after running a generator and validate the return value's type. But I think this is not possible because the PHPDoc of a function is not linked with a generator.

**Comment by SOF3** [comment]
> > I don't understand what you mean. Who parses this doc? When does it parse this doc?
> 
> Await-generator should parse the doc after running a generator and validate the return value's type. But I think this is not possible because the PHPDoc of a function is not linked with a generator.

no more runtime checks please. this should be done in static analysis. don't waste runtime performance like PHP did.

also await-generator doesn't even have your generator if you use `yield from`.
