### ISSUE TITLE
Undefined variable $name

### ISSUE THREAD

**Issue by LordFit** [SOF3/await-generator#202]
`SOFe\AwaitGenerator\AwaitException: "Unhandled async exception: Undefined variable $name" (EXCEPTION) in "/root/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await" at line 587`

Help

**Comment by Endermanbugzjfc** [comment]
Additional conversations can be found on the PocketMine-MP Discord:
https://discord.com/channels/373199722573201408/480650036972224513/1135919233981751357
