### ISSUE TITLE
Errer

### ISSUE THREAD

**Issue by vkamz597** [SOF3/await-generator#205]
Unhandled async exception: Position world is null or has been unloaded
File: /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await
Line: 587
Type: SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(334): SOFe\AwaitGenerator\Await->reject(object pocketmine\utils\AssumptionFailedError#1000839)
#1 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#1038912)
#2 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#1038912)
#3 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#1226974)
#4 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(124): SOFe\AwaitGenerator\AwaitChild->resolve()
#5 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\SqlResult#1208972)
#6 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
#7 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#8 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[17], null)
#9 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
#11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#13 pmsrc/src/Server(1683): pocketmine\snooze\SleeperHandler->sleepUntil(float 1699953122.1125)
#14 (): [33m--- below is the original stack trace ---[m()
#15 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(223): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(array[1], array[1], array[1], object Closure#1230929, object Closure#1229989)
#16 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(180): poggit\libasynql\base\DataConnectorImpl->executeImpl(string[29] bcp.generic.begin_transaction, array[0], int 0, object Closure#1230929, object Closure#1229989)
#17 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(122): poggit\libasynql\base\DataConnectorImpl->executeImplLast(string[29] bcp.generic.begin_transaction, array[0], int 0, object Closure#1231765, object Closure#1229989)
#18 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(132): poggit\libasynql\base\DataConnectorImpl->executeGeneric(string[29] bcp.generic.begin_transaction, array[0], object Closure#1229948, object Closure#1229989)
#19 plugins/BedcoreProtect-stable/src/matcracker/BedcoreProtect/storage/queries/BlocksQueries(262): poggit\libasynql\base\DataConnectorImpl->asyncGeneric(string[29] bcp.generic.begin_transaction)
#20 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(114): matcracker\BedcoreProtect\storage\queries\BlocksQueries->matcracker\BedcoreProtect\storage\queries\{closure}()
#21 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Mutex(103): SOFe\AwaitGenerator\Mutex->run(object Generator#818296)
#22 (): SOFe\AwaitGenerator\Mutex->runClosure(object Closure#679801)
#23 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(376): Generator->send(object Closure#1229989)
#24 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(332): SOFe\AwaitGenerator\Await->SOFe\AwaitGenerator\{closure}()
#25 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(317): SOFe\AwaitGenerator\Await->wakeup(object Closure#1230922)
#26 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/Await(552): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#1230922)
#27 /home/user/pm/virions/await-generator_dev-130.phar/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#1229965)
#28 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(165): SOFe\AwaitGenerator\AwaitChild->resolve(array[2])
#29 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(156): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(int 388910, int 1)
#30 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(181): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlInsertResult#1191444)
#31 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(239): poggit\libasynql\base\DataConnectorImpl::poggit\libasynql\base\{closure}(array[1])
#32 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#33 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[12], null)
#34 /home/user/pm/virions/libasynql_dev-204.phar/src/poggit/libasynql/base/SqlThreadPool(64): poggit\libasynql\base\DataConnectorImpl->checkResults()
#35 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
#36 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#37 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#38 pmsrc/src/Server(1683): pocketmine\snooze\SleeperHandler->sleepUntil(float 1699953121.9125)
#39 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
#40 pmsrc/src/PocketMine(341): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[14] /home/user/pm/, string[22] /home/user/pm/plugins/)
#41 pmsrc/src/PocketMine(364): pocketmine\server()
#42 pmsrc(11): require(string[58] phar:///home/user/pm/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Endermanbugzjfc** [comment]
I am sorry that you have encountered this error message. However, I would like to clarify that this issue is caused by a faulty plugin (BedcoreProtect, see trace `#19`) that are using the Await-generator library and is not indicative of any issue with the library itself.

If you are experiencing this error, I recommend that you look at the crash-dump for more information, and try to reach out to the creator of the plugin.

I appreciate your understanding and patience to resolve this issue.
