### ISSUE TITLE
Crash !!

### ISSUE THREAD

**Issue by GabBiswajit** [SOF3/await-generator#207]
`hex2bin()` At Line 588 in Await!!
Look at this fast!

**Comment by Endermanbugzjfc** [comment]
Please provide more details for further follow up, such as the crashdump URL.

**Comment by GabBiswajit** [comment]
Thread: Main
Error: Unhandled async exception: hex2bin(): Input string must be hexadecimal string
File: plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/Await
Line: 588
Type: SOFe\AwaitGenerator\AwaitException
Backtrace:
#0 plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/Await(335): SOFe\AwaitGenerator\Await->reject(object ErrorException#40808)
#1 plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/Await(318): SOFe\AwaitGenerator\Await->wakeup(object Closure#40850)
#2 plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/Await(553): SOFe\AwaitGenerator\Await->wakeupFlat(object Closure#40850)
#3 plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/AwaitChild(52): SOFe\AwaitGenerator\Await->recheckPromiseQueue(object SOFe\AwaitGenerator\AwaitChild#45053)
#4 /home/container/virions/libasynql_dev-207.phar/src/poggit/libasynql/base/DataConnectorImpl(239): SOFe\AwaitGenerator\AwaitChild->resolve(array[1])
#5 /home/container/virions/libasynql_dev-207.phar/src/poggit/libasynql/base/SqlThreadPool(116): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(array[1])
#6 /home/container/virions/libasynql_dev-207.phar/src/poggit/libasynql/base/DataConnectorImpl(322): poggit\libasynql\base\SqlThreadPool->readResults(array[1], null)
#7 (): --- below is the original stack trace ---()
#8 plugins/AuctionHouse-pm5/src/shock95x/auctionhouse/database/Database(80): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(array[1], array[1], array[1], object Closure#41106, object Closure#45317)
#9 plugins/AuctionHouse-pm5/src/SOFe/AwaitGenerator/Await(303): shock95x\auctionhouse\database\Database->shock95x\auctionhouse\database\{closure}(object Closure#41106, object Closure#45317)
#10 plugins/AuctionHouse-pm5/src/shock95x/auctionhouse/database/Database(81): SOFe\AwaitGenerator\Await::promise(object Closure#40855)
#11 plugins/AuctionHouse-pm5/src/shock95x/auctionhouse/task/ListingExpireTask(27): shock95x\auctionhouse\database\Database->asyncSelectRaw(string[44] SELECT * from listings WHERE expired = TRUE;)

**Comment by Endermanbugzjfc** [comment]
I am sorry that you have encountered this error. However, I would like to clarify that this issue is caused by a faulty plugin (AuctionHouse, according to the stacktrace) that are using the Await-generator library and is not indicative of any issue with the library itself.

If you are experiencing this error, I recommend that you look at the problematic code instead and try to reach out to the creator of the plugin, shock95x.

I appreciate your understanding and patience to resolve this issue.
